### ISSUE TITLE
Is it possible to remove 'fill' attributes from the svg?

### ISSUE THREAD

**Issue by yhanssens** [swisnl/laravel-mix-svg-sprite#3]
I believe this is possible with svgo but I'm not sure how to extend or change the config.

**Comment by JaZo** [comment]
Hi @yhanssens, this plugin uses the same SVGO-options Mix uses. The following example demonstrates how you can change these options.

``` js
mix.options({
    imgLoaderOptions: {
        svgo: { // N.B. Use false to disable SVGO completely
            cleanupIDs: { prefix: 'foo' }
        }
    }
});
```
I don't know if it's possible with SVGO and what exact option you need, but all available options can be found on https://github.com/svg/svgo#what-it-can-do
