### ISSUE TITLE
Bug : Mix reload on a vue.js SPA doesn't load the icons

### ISSUE THREAD

**Issue by Epistol** [swisnl/laravel-mix-svg-sprite#6]
## Detailed description

I'm trying to do a project in Laravel coupling VueJS as an SPA and using your library, but something weird occur : 

When i first run mix with browserSync, the website shows itself perfectly with all icons as svg, but when a change of code occurs, the website "hot reload" and all the icons generated by the library disappear ! 

And the same error occur when you open the website twice, the first tab could be perfect but the new one won't have any svg generated.

* Version used (e.g. Node 10 and Laravel Mix 4.0):

`
"laravel-mix": "^4.1.2",
"laravel-mix-svg-sprite": "^1.0.0",
"svg-spritemap-webpack-plugin": "^3.4.0",
 "svg4everybody": "^2.1.9",
"vue": "^2.6.10",
 "vuex": "^3.1.1",
`

* Operating system and version (e.g. Ubuntu 16.04, Windows 10):

Mac OS

* Link to your project or minimal working example:

Webpack : https://gist.github.com/Epistol/127330e1e31fdd37b441b1dbd22025be

The SPA router of VueJS : https://gist.github.com/Epistol/227e8d55ff07a5ed898ba3f4bab6800f

app.js : https://gist.github.com/Epistol/d8eae61ee32ef49031574c13fd37ebce

And an exemple loading svg of my vue component page : 

```
<svg class="fill-current w-full h-full">
                                <use xlink:href="/svg/sprite.svg#help"/>
                            </svg>
```

**Comment by Epistol** [comment]
@JaZo  maybe ?

**Comment by JaZo** [comment]
[Your usage](https://gist.github.com/Epistol/127330e1e31fdd37b441b1dbd22025be#file-webpack-mix-js-L29) of this plugin is not as [documented](https://github.com/swisnl/laravel-mix-svg-sprite#usage). Please read the documentation and verify you use it correctly.

**Comment by SergisGit** [comment]
does not work with laravel-mix 4.
this works correctly:
https://www.npmjs.com/package/@ayctor/laravel-mix-svg-sprite/v/1.0.0

**Comment by JaZo** [comment]
Based on @SergisGit's comment I assume this issue is not meant for our package, but for [@ayctor/laravel-mix-svg-sprite](https://www.npmjs.com/package/@ayctor/laravel-mix-svg-sprite/v/1.0.0), so I'll close this issue.

**Comment by SergisGit** [comment]
> Based on @SergisGit's comment I assume this issue is not meant for our package, but for [@ayctor/laravel-mix-svg-sprite](https://www.npmjs.com/package/@ayctor/laravel-mix-svg-sprite/v/1.0.0), so I'll close this issue.

lol what? Man, your package does not work! It has wrong initialization on this moment.
